DebateUs/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView, RedirectView


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# slop that needs to be cleaned up after full definition

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='arguemeter/', permanent=False), name='base_view'),

    # Examples:
    # url(r'^$', 'DebateUs.views.home', name='home'),
    # url(r'^DebateUs/', include('DebateUs.foo.urls')),
    url(r'^arguemeter/', include('arguemeter.urls', namespace='arguemeter')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^grappelli/', include('grappelli.urls')),  # grappelli URLS
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^oauth2/', include('provider.oauth2.urls', namespace='oauth2')),
    url(r'^accounts/signup/', RedirectView.as_view(url='/landing/', permanent=False), name='signup'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^landing/', include('landing.urls', namespace='landing')),
)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns+=patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

arguemeter/urls.py
# Core Django imports
from django.conf.urls import patterns, url, include

# Third party imports
from rest_framework import routers

# App-specific imports
from arguemeter import views
from messages import views as msg_views

__author__ = 'archen'

router = routers.DefaultRouter()
router.register(r'topics', views.TopicViewSet)
router.register(r'article', views.ArticleViewSet)
router.register(r'ratings', views.RatingViewSet)
router.register(r'tags', views.ReasonTagViewSet)
router.register(r'citations', views.CitationViewSet)
router.register(r'inbox', msg_views.InboxViewSet)
router.register(r'messages', msg_views.MessageViewSet)

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),

    # Topic URLs
    url(r'^topics/add/quick/$', views.topic_add_view, name='add-quick-topic'),
    url(r'^topics/(?P<pk>\d+)/edit$', views.TopicUpdate.as_view(), name='edit-topic'),
    url(r'^topics/(?P<pk>\d+)/delete', views.delete_topic, name='delete-topic'),
    url(r'^topics/(?P<pk>\d+)/articles/$', views.topic_articles_list_view, {'context': None}, name='list-articles'),
    url(r'^topics/(?P<pk>\d+)/citations/add/$', views.topic_citation_add_view,
        name='add-citation-topic'),
    url(r'^topics/(?P<pk>\d+)/ratings/(?P<rating_id>\d+)/attach/$', views.attach_rating,
        name='attach-rating'),
    url(r'^topics/(?P<pk>\d+)/ratings/(?P<rating_id>\d+)/remove/$', views.remove_rating,
        name='remove-rating'),
    url(r'^topics/(?P<pk>\d+)/axescats/(?P<axescat_id>\d+)/attach/$', views.attach_axescat,
        name='attach-axescat'),
    url(r'^topics/(?P<pk>\d+)/axescats/(?P<axescat_id>\d+)/remove/$', views.remove_axescat,
        name='remove-axescat'),
    url(r'^topics/(?P<topic_id>\d+)/favorite/attach/$', views.attach_favorite,
        name='attach-favorite'),
    url(r'^topics/(?P<topic_id>\d+)/favorite/remove/$', views.remove_favorite,
        name='remove-favorite'),

    # Article URLs
    url(r'^topics/(?P<pk>\d+)/articles/add/quick/$', views.article_add_view,
        name='add-quick-article'),
    url(r'^articles/(?P<pk>\d+)/edit$', views.ArticleUpdate.as_view(), name='edit-article'),
    url(r'^articles/(?P<pk>\d+)/delete$', views.delete_article, name='delete-article'),
    url(r'^articles/(?P<pk>\d+)$', views.article_detail_view, name='detail-article'),
    url(r'^articles/(?P<pk>\d+)/citations/add/$', views.article_citation_add_view,
        name='add-citation-article'),
    url(r'^articles/(?P<pk>\d+)/comments/add/$', views.comment_add_view,
        name='add-comment'),
    url(r'^articles/(?P<pk>\d+)/ratings/add/$', views.ratings_add_view,
        name='add-ratings'),

    url(r'^articles/(?P<article_id>\d+)/tags/(?P<pk>\d+)/dis_agrees/add/$', views.add_tag_dis_agree, name='add-tag-disagree'),


    url(r'^comments/(?P<pk>\d+)/dis_agrees/add/$', views.add_comment_dis_like,
        name='add-comment-dislike'),
    url(r'^profile/$', views.profile_view, name='view-profile'),
    url(r'^profile/(?P<pk>\d+)/edit/$', views.ProfileUpdate.as_view(), name='edit-profile'),

    url(r'^messages/', msg_views.inbox_all, name='messages'),

    url(r'^api/', include(router.urls)),

    url(r'^assets/$', views.assets)

)

landing/urls.py
# urls for landing app
from django.conf.urls import patterns, url
from landing import views

urlpatterns = patterns('',
                       url(r'^$', view=views.index, name='index'),
                       url(r'^add-invite/$', view=views.add_invite, name='add-invite')
                       )

arguemeter/views.py
# Core Python imports
import ast
from datetime import datetime
from exceptions import ValueError
from itertools import chain

# Core Django imports
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.core.urlresolvers import reverse_lazy
from django.db.models import Count, Sum
from django.db.utils import IntegrityError
from django.http import HttpResponse, HttpResponseServerError
from django.shortcuts import redirect, render, get_object_or_404
from django.utils.timezone import utc
from django.views.generic.edit import UpdateView

# Third Party imports
from braces.views import LoginRequiredMixin
# from guardian.shortcuts import assign_perm, get_objects_for_user

# Application imports
from rest_framework import viewsets, generics
from rest_framework.response import Response
from arguemeter.serializers import TopicSerializer, RatingSerializer, AxesCategorizationSerializer, CitationSerializer, \
    ArticleSerializer, ReasonTagSerializer
from .forms import ArticleForm, CitationForm, CommentForm, TopicForm, LinkForm, LinkSummaryForm
# from community.authorization import permission_required_or_403
# from community.models import Community, CommunityTag
from core.models import Article, AxesCategorization, Citation, Comment, DisAgree, DisAgreeAxis, DisLike, Rating, \
    RatingCriteria, Topic, Link, LinkSummary, ReasonTag, DisAgreeTag, TopicFavorite
from core import rater
from core.authorization import ArticleOwnerMixin, TopicOwnerMixin, UserOwnerMixin, is_article_owner, \
    is_not_article_owner, is_topic_owner


class TopicViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows topics to be viewed or edited.
    """
    queryset = Topic.objects.filter(deleted=False)
    serializer_class = TopicSerializer

    def destroy(self, request, *args, **kwargs):
        topic = self.get_object()
        topic.deleted = True
        topic.save()


class ArticleViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows articles to be viewed or edited.
    """
    queryset = Article.objects.filter(deleted=False)
    serializer_class = ArticleSerializer
    filter_fields = ('topic__id',)

    def destroy(self, request, *args, **kwargs):
        article = self.get_object()
        article.deleted = True
        article.save()


class RatingViewSet(viewsets.ModelViewSet):
    serializer_class = RatingSerializer
    queryset = Rating.objects.filter(deleted=False).order_by('order')
    filter_fields = ('topic__id', 'name', 'is_default')

    def create(self, request, *args, **kwargs):
        try:
            post = request.POST
            rating = Rating(name=post['name'], description=post['name'], weight=post['weight'],
                            date_created=datetime.utcnow().replace(tzinfo=utc),
                            date_last_edited=datetime.utcnow().replace(tzinfo=utc), owner=request.user)
            rating.save()
            return Response(data=self.serializer_class(rating).data)
        except:
            return HttpResponseServerError()

    def destroy(self, request, *args, **kwargs):
        params = request.QUERY_PARAMS
        if 'topic_id' in params:
            rating = Rating.objects.get(id=kwargs.get('pk'))
            topic = Topic.objects.get(id=params['topic_id'])
            rating.topic.remove(topic)
            return HttpResponse()
        else:
            return super(RatingViewSet, self).destroy(request, args, kwargs)

    def list(self, request, *args, **kwargs):
        params = request.QUERY_PARAMS
        if params.get('is_current_user'):
            queryset = Rating.objects.filter(name=params.get('name'), owner=request.user)
            serializer = self.serializer_class(queryset, many=True)
            return Response(serializer.data)
        else:
            return super(RatingViewSet, self).list(request, args, kwargs)


class AxesCategorizationViewSet(viewsets.ModelViewSet):
    serializer_class = AxesCategorizationSerializer
    queryset = AxesCategorization.objects.filter(deleted=False)
    filter_fields = ('topic__id', 'article__id', 'name',)

    def get_queryset(self):
        queryset = super(AxesCategorizationViewSet, self).get_queryset()

        topic_id = self.request.query_params.get('-topic__id', None)
        article_id = self.request.query_params.get('-article__id', None)

        if topic_id:
            queryset = queryset.exclude(topic__id=topic_id)

        if article_id:
            queryset = queryset.exclude(article__id=article_id)

        return queryset

    def destroy(self, request, *args, **kwargs):
        params = request.QUERY_PARAMS
        if 'topic_id' in params:
            axes_cat = AxesCategorization.objects.get(id=kwargs.get('pk'))
            topic = Topic.objects.get(id=params['topic_id'])
            axes_cat.topic.remove(topic)
            return HttpResponse()
        else:
            return super(AxesCategorizationViewSet, self).destroy(request, args, kwargs)


class ReasonTagViewSet(viewsets.ModelViewSet):
    serializer_class = ReasonTagSerializer
    queryset = ReasonTag.objects.filter(deleted=False)
    filter_fields = ('topic__id', 'article__id', 'name',)

    def get_queryset(self):
        queryset = super(ReasonTagViewSet, self).get_queryset()

        # add exclusion behavior
        topic_id_exclude = self.request.query_params.get('-topic__id', None)
        article_id_exclude = self.request.query_params.get('-article__id', None)

        if topic_id_exclude:
            queryset = queryset.exclude(topic__id=topic_id_exclude)

        if article_id_exclude:
            queryset = queryset.exclude(article__id=article_id_exclude)

        return queryset

    def create(self, request, *args, **kwargs):
        post = request.POST
        tag = ReasonTag(name=post['name'], user=request.user)
        tag.save()
        return Response(data=self.serializer_class(tag).data)

    def destroy(self, request, *args, **kwargs):
        params = request.QUERY_PARAMS
        if 'topic_id' in params:
            tag = self.get_object()
            topic = Topic.objects.get(id=params['topic_id'])
            tag.topic.remove(topic)
            return HttpResponse()
        elif 'article_id' in params:
            tag = self.get_object()
            article = Article.objects.get(id=params['article_id'])
            tag.article.remove(article)
            tag.topic.remove(article.topic)
            return HttpResponse()
        else:
            return super(ReasonTagViewSet, self).destroy(request, args, kwargs)


class CitationViewSet(viewsets.ModelViewSet):
    serializer_class = CitationSerializer
    queryset = Citation.objects.filter(deleted=False)
    filter_fields = ('topic__id', 'article__id',)


class ArticleUpdate(LoginRequiredMixin, ArticleOwnerMixin, UpdateView):
    model = Article
    form_class = ArticleForm

    login_url = "/accounts/login/"

    def post(self, request, *args, **kwargs):
        result = super(ArticleUpdate, self).post(request, args, kwargs)

        article = self.object

        # new article needs user/author set
        if not article.user:
            article.user = request.user
            article.save()

        # save axes
        # for axes_cat_id in request.POST.getlist('axes_use[]'):
        #     axes_cat = AxesCategorization.objects.get(pk=axes_cat_id)
        #     axes_cat.article.add(article)
        #     axes_cat.used_by.add(request.user)
        #     axes_cat.save()
        # save tags
        for tag_id in request.POST.getlist('tag_use[]'):
            tag = ReasonTag.objects.get(pk=tag_id)
            tag.article.add(article)
            tag.topic.add(article.topic)
            tag.used_by.add(request.user)
            tag.save()
        # save citations
        for citation_text, citation_link, citation_id in zip(request.POST.getlist('citation_text[]'),
                                                             request.POST.getlist('citation_link[]'),
                                                             request.POST.getlist('citation_id[]')):
            if not citation_id:
                citation = Citation(user_id=request.user.id, article=article, text=citation_text,
                                    link=citation_link, date_created=datetime.utcnow().replace(tzinfo=utc),
                                    date_last_edited=datetime.utcnow().replace(tzinfo=utc))
                citation.save()

        # check for link (shared article) update
        if request.POST.get('shared_link_id'):
            link_summary = LinkSummary.objects.get(id=request.POST.get('shared_link_id'))
            link_summary.author = request.POST.get('author')
            link_summary.title = request.POST.get('title')
            link_summary.summary = request.POST.get('summary')

            if link_summary.link.full_url != request.POST.get('full_url'):
                existing = Link.objects.filter(full_url=request.POST.get('full_url'))
                if existing.exists():
                    link_summary.link = existing.get()
                else:
                    link = Link(full_url=request.POST.get('full_url'))
                    link.save()
                    link_summary.link = link
            link_summary.save()

            article.content = request.POST.get('summary')
            article.save()

        return result


class TopicUpdate(LoginRequiredMixin, TopicOwnerMixin, UpdateView):
    model = Topic
    form_class = TopicForm

    login_url = "/accounts/login/"

    def post(self, request, *args, **kwargs):

        result = super(TopicUpdate, self).post(request, args, kwargs)

        if result.status_code == 200 or result.status_code == 302:

            topic = self.object

            # new topic needs user/author set
            if not topic.user:

core/views.py
# Create your views here.

arguemeter/templates/core/article_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-default" type="submit">submit</button>
</form>

{%  endblock %}

arguemeter/templates/core/article_update_modal.html
{% load crispy_forms_tags %}
    <form class="form-horizontal" method="post" id="articleUpdateModalForm" data-bind="attr: { action: url }">
        <fieldset>
            <div class="modal" id="articleUpdateModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div class="form-group pull-right clearfix">
                                <button type="submit" class="btn btn-default pull-right">Save</button>
                                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Cancel
                                </button>
                                <a data-bind="attr: { href: deleteUrl  }, visible: id" class="btn btn-default pull-right"
                                       onclick="return confirm('Really delete this article?')">Delete</a>
                            </div>
                            <h4 class="modal-title">Add an article</h4>
                        </div>
                        <div class="modal-body clearfix">

                            {% csrf_token %}

                            <div class="shared-link-update">

                                {% crispy shared_form_pg1 %}

                            </div>

                            <div class="article-content-update">

                                {% crispy update_form %}

                            </div>

                            <div class="shared-link-update">

                                {% crispy shared_form_pg2 %}

                                <input type="hidden" name="shared_link_id" data-bind="value: shared_link_id"/>

                            </div>
                            <div class="col-md-6">

                                <h5>Reason Tags</h5>

                                <div>
                                    {#                                    <input type="text" placeholder="Enter new reason tag" data-bind="value: tagToAdd"/>#}
                                    <select data-bind="options: unusedTags, value: tagToAdd, optionsCaption: 'Add reason tag', optionsText: 'name'"></select>
                                    <a href="#" data-bind="click: addTag, enable: canAddTag"><span
                                            class="glyphicon glyphicon-plus-sign"></span></a>
                                    <label class="text-warning" data-bind="visible: tags().length >= 5">Maximum of 5
                                        tags allowed per argument</label>
                                </div>
                                <div data-bind="foreach: tags">
                                    <div class="data">
                                        <a href="#" data-bind="click: $parent.removeTag"><span
                                                class="glyphicon glyphicon-remove-circle"></span></a>
                                        <span data-bind="text: name"></span>
                                    </div>
                                    <input type="hidden" name="tag_use[]" data-bind="value: id"/>
                                </div>

                                <h5>Cite Sources</h5>

                                <div>
                                    <input type="text" placeholder="Source URL" data-bind="value: citationLinkToAdd"/>
                                    <a href="#"
                                       data-bind="click: addCitation, enable: citationLinkToAdd.length > 0 && citationTextToAdd.length > 0">
                                        <span class="glyphicon glyphicon-plus-sign"></span>
                                    </a>
                                    <input type="text" placeholder="Source title" data-bind="value: citationTextToAdd"/>
                                </div>
                                <div data-bind="foreach: citations">
                                    <div class="data"><a href="#" data-bind="click: $parent.removeCitation"><span
                                            class="glyphicon glyphicon-remove-circle"></span></a><a
                                            data-bind="attr: {href: link}, text: text"></a></div>
                                    <input type="hidden" name="citation_text[]" data-bind="value: text">
                                    <input type="hidden" name="citation_link[]" data-bind="value: link">
                                    <input type="hidden" name="citation_id[]" data-bind="value: id">
                                </div>
                            </div>

                            <input id="article-id" type="hidden" data-bind="value: id"/>

                            <div class="col-md-12">
                                <div class="modal-footer">
                                    <a data-bind="attr: { href: deleteUrl }, visible: id" class="btn btn-default"
                                       onclick="return confirm('Really delete this article?')">Delete</a>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel
                                    </button>
                                    <button type="submit" class="btn btn-default">Save</button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </form>

arguemeter/templates/core/assets.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block page_title %}
    Assets
{% endblock page_title %}


{% block extra_css %}

    <style type="text/css">
    .colorBlocks > * {
        border: solid 1px black;
        height: 50px;
    }
    </style>
{% endblock %}


{% block content %}


    <div class="container">

        <div class="row colorBlocks">
            <div class="col-md-1" style="background-color: #E06666">
                Header
            </div>
            <div class="col-md-1" style="background-color: #E06666">
                Border
            </div>
            <div class="col-md-1" style="background-color: #FFFFFF">
                Font Light
            </div>
            <div class="col-md-1" style="background-color: #000000; color: white;">
                Font Dark
            </div>
            <div class="col-md-1" style="background-color: #b7b7b7">
                Button
            </div>
            <div class="col-md-1" style="background-color: #f3f3f3">
                Text Area
            </div>
            <div class="col-md-1" style="background-color: #cc0000">
                Fill
            </div>
            <div class="col-md-1" style="background-color: #990000">
                Hover
            </div>
            <div class="col-md-1" style="background-color: #999999">
                Tile Dark
            </div>
        </div>

    </div>
{% endblock %}

arguemeter/templates/core/citation_form.html
{% load crispy_forms_tags %}


<form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-default" value="Close" name="_cancel">
    <input type="submit" class="btn btn-default" value="Save & Add Another" name="_addanother">
    <input type="submit" class="btn btn-default" value="Save" name="_save">

</form>

arguemeter/templates/core/citation_form_view.html
{% extends "base.html" %}

{% load templatetags %}
{% load crispy_forms_tags %}

{% block content %}

{% add_citation form %}

{% endblock %}

arguemeter/templates/core/citation_list.html
{% if cols > 0 %}<div class="col-md-{{ cols }} {{ class_str }}">{% endif %}

    <div id="citation_list_module" class="list-group">
        <div class="list-group-item list-group-header">Sources</div>
        {% if not citations.exists %}
            <div class="list-group-item">
                No sources have been added.
            </div>
        {% endif %}
        {% for citation in citations %}
            <div class="list-group-item">
                {% if citation.link %}<a href="{{ citation.link }}" target="_blank">{% endif %}
                {{ citation.text }}{% if citation.is_truncated %}&#8230;{% endif %}
                {% if citation.link %}</a>{% endif %}
            </div>
        {% endfor %}
    </div>

{% if cols > 0 %}</div>{% endif %}

arguemeter/templates/core/comment_form.html
{# parent (adds a collapse button), article_id (indicates article that will be submitted for), #}

{% load crispy_forms_tags %}


<form {% if parent %} id="reply_to_{{ parent }}" {% endif %}class="form-horizontal {% if parent %}collapse{% endif %}" action="{% url 'arguemeter:add-comment' article_id %}" method="post">
    <fieldset>
        {% csrf_token %}
        {% if parent %}<legend>Reply to Comment</legend>{% else %}Add Comment</legend>{% endif %}
        <div class="comment-input">
            {% crispy comment_form %}
        </div>
        {% if parent %}<input type="hidden" value="{{ parent }}" name="parent"/>{% endif %}
        <button class="btn btn-primary" type="submit">Save</button>
        {% if parent %}<a href="javascript:void(0)" onclick="$('#reply_to_{{ parent }}').hide()">Cancel</a>{% endif %}
    </fieldset>
</form>

arguemeter/templates/core/filter_form.html
    <input class="search" type="search" placeholder="Search {{ title }}">
    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>

    <div class="dropdown sort-dropdown">
        <button class="list-group-item dropdown-toggle" type="button" data-toggle="dropdown">
            Sort By:
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
            {% if title == 'Articles' %}
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" onclick="$('input[name=orderby]').val('-rating_score').closest('form').submit();return false">
                Highest Rating
                </a>
            </li>
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" onclick="$('input[name=orderby]').val('-num_comments').closest('form').submit();return false">
                    Most Comments
                </a>
            </li>
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" onclick="$('input[name=orderby]').val('-date_last_edited').closest('form').submit();return false">
                    Most Recent
                </a>
            </li>
            {% endif %}

            {% if title == 'Topics' %}
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" onclick="$('input[name=orderby]').val('-date_created').closest('form').submit();return false">
                    Newest Topics
                </a>
            </li>
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" onclick="$('input[name=orderby]').val('-article_date_last_edited').closest('form').submit();return false">
                    Recent Arguments
                </a>
            </li>
            <li role="presentation">
                <a role="menuitem" tabindex="-1" href="#" onclick="$('input[name=orderby]').val('-n_articles').closest('form').submit();return false">
                    Most Arguments
                </a>
            </li>
            {% endif %}

            {% for sort_type in sort_type_list %}
                <li role="presentation"><a role="menuitem" tabindex="-1" href="#">{{ sort_type }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="filter_axes_group">
        {% for axes in filter_axes %}
            <div class="filter_axis">
                {{ axes.name }}
                <input type="range" name="points" min="1" max="10"/>
            </div>
        {% endfor %}
    </div>

    <input type="hidden" name="orderby" value="-rating_score"/>


    {% csrf_token %}

arguemeter/templates/core/sub_nav.html
<!--
    Note when using this tag - for embedly to work, the embedly lib and setup script need to be on the page
-->

{% load crispy_forms_tags %}
{% load staticfiles %}

<div class="sub-nav-wrapper">
    <div class="sub-nav">
        <ul>
            <li>
                <a href="{% url 'arguemeter:list-articles' topic.id %}" class="btn btn-primary selected slim">Arguments</a>
            </li>
            <li>
                <button class="btn btn-default slim" data-toggle="modal" data-target="#articleUpdateModal"
                        data-articleid="" data-topicid="{{ topic.id }}" data-bind="click: init">Write Argument</button>
            </li>
            <li>
                <button class="btn btn-default slim" data-toggle="modal" data-target="#articleUpdateModal"
                        data-articleid="" data-topicid="{{ topic.id }}" data-newshared="true" data-bind="click: init">
                    Share Argument</button>
            </li>
            <li>
                <button class="btn btn-default slim" data-target="#topicDescriptionModal" data-toggle="modal">Topic Details
                </button>
            </li>
        </ul>
    </div>
</div>

arguemeter/templates/core/topic_description.html
{% load crispy_forms_tags %}
{% load templatefilters %}

            <div class="modal" id="topicDescriptionModal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <div class="form-group pull-right clearfix">
                                <button type="button" class="btn btn-default pull-right" data-dismiss="modal">Close
                                </button>
                            </div>
                            <h4 class="modal-title">Topic Details</h4>
                        </div>
                        <div class="modal-body clearfix">
                            <div class="col-md-9 topic-title">
                                {{ topic.topic_name }}
                            </div>
                            <div class="col-md-3 details">
                                <label>Created by {{ topic.display_author }}</label>
                            </div>
                            <div class="col-md-12 topic-description">
                                <p>
                                    {% if not topic.detail %}

                                        <em>There is no topic description for this topic.</em>

                                    {% endif %}
                                    {{ topic.detail | bbcode }}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

arguemeter/templates/core/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-default" type="submit">submit</button>
</form>

{%  endblock %}